export const OPERATION_UNIT_STATUS = {
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE'
}

export const FETCH_COMPANY_REQUEST = "FETCH_COMPANY_REQUEST"
export const FETCH_CUSTOMERS_REQUEST = "FETCH_CUSTOMERS_REQUEST"
